### ISSUE TITLE
default_values added to dictionary fields

### ISSUE THREAD

**Issue by mdbecker** [allancaffee/scaly-mongo#4]
If your model has a field that is a dictionary and you have default values set for your model; scaly-mongo will add the default values to the contents of the dictionary field when saving the model.

Example:

```
from scalymongo import Document


class Theme(Document):

    __collection__ = 'themes'

    structure = {
        'name': unicode,
        'layout': [unicode],
        'dictionary': dict,
    }

    required_fields = set([
        'name',
        'layout',
        'dictionary',
    ])

    default_values = {
        'layout': list,
        'dictionary': dict,
    }


    theme = Theme({
        'dictionary': {'foo': '1', 'bar': '2'},
        'layout': [u'foo', u'bar'],
        'name': u'Testing 1 2 3',
    })

    print Theme.find_one({'_id': cls.theme._id})
```

Prints:

```
{u'_id': ObjectId('4e7a3f97f64aa0468b00001a'), 'layout': [u'foo', u'bar'], u'name': u'Testing 1 2 3', 'dictionary': {u'bar': u'2', u'foo': u'1', 'layout': [], 'dictionary': {}}}
```

Without default_values the behavior is as expected:

```
{u'_id': ObjectId('4e7a43e8f64aa046ee00001a'), u'layout': [u'foo', u'bar'], u'name': u'Testing 1 2 3', u'dictionary': {u'foo': u'1', u'bar': u'2'}}
```

**Comment by allancaffee** [comment]
It turns out that the issue behind this was the misuse of the `as_class` parameter to `find` and `find_one`. The `as_class` argument to `find_one` apparently wraps _all_ subdocuments in the returned result.  In other words if you have a class called `Theme` any dicts that were in the returned document would also be cast as `Theme`s. This leads to the strange behavior where embedded documents pick up defaults set up for the model class.
